### ISSUE TITLE
Unable to run `./yii_test` due to `cookieValidationKey` unknown property error

### ISSUE THREAD

**Issue by ricpelo** [yiisoft/yii2-app-advanced#346]
### What steps will reproduce the problem?

```sh
$ composer create-project --prefer-dist yiisoft/yii2-app-advanced advanced
$ cd advanced
$ ./init
(choose 0 -> Development)
$ vi common/config/main-local.php  # set database config
$ vi common/config/test-local.php  # set database config
$ ./yii_test
```

### What's expected?

`./yii_test` works without any errors.

### What do you get instead?

`./yii_test` fails to run with the following error message:

```sh
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::cookieValidationKey'

in /home/ricardo/web/advanced/vendor/yiisoft/yii2/base/Component.php:209

Stack trace:
#0 /home/ricardo/web/advanced/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('cookieValidatio...', 'test')
#1 /home/ricardo/web/advanced/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(yii\console\Request), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /home/ricardo/web/advanced/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#4 /home/ricardo/web/advanced/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\console\\Req...', Array, Array)
#5 /home/ricardo/web/advanced/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\console\\Req...', Array, Array)
#6 /home/ricardo/web/advanced/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#7 /home/ricardo/web/advanced/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
#8 /home/ricardo/web/advanced/vendor/yiisoft/yii2/console/Application.php(219): yii\base\Module->get('request')
#9 /home/ricardo/web/advanced/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->getRequest()
#10 /home/ricardo/web/advanced/yii_test(22): yii\base\Application->run()
#11 {main}
```

If I put the following source code line before create the `Application` instance, then it works OK:

```php
unset($config['components']['request']);
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.14
| PHP version      | 7.2.2-3+ubuntu16.04.1+deb.sury.org+1
| Operating system | Ubuntu 16.04.3 LTS

**Comment by samdark** [comment]
components.request.cookieValidationKey should be configured.

**Comment by biaoqianwo** [comment]
`./yii_test migrate` and `codecept run` are conflict.

1.If common\config\test.php has:
```
        'request' => [
            'class' => '\yii\web\Request',
            'enableCookieValidation' => false,
        ],
```
`./yii_test migrate` cannot be run succesefully. 
And `codecept run` is ok.


2.If common\config\test.php has:
```
        'request' => [
            'class' => '\yii\console\Request',
            'enableCookieValidation' => false,
        ],
```
`./yii_test migrate` will has an error:
```
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::enableCookieValidation'

in /home/lijun/works/yii-application/vendor/yiisoft/yii2/base/Component.php:209

Stack trace:
#0 /home/lijun/works/yii-application/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('enableCookieVal...', false)
#1 /home/lijun/works/yii-application/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(yii\console\Request), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /home/lijun/works/yii-application/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#4 /home/lijun/works/yii-application/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('\\yii\\console\\Re...', Array, Array)
#5 /home/lijun/works/yii-application/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('\\yii\\console\\Re...', Array, Array)
#6 /home/lijun/works/yii-application/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#7 /home/lijun/works/yii-application/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
#8 /home/lijun/works/yii-application/vendor/yiisoft/yii2/console/Application.php(219): yii\base\Module->get('request')
#9 /home/lijun/works/yii-application/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->getRequest()
#10 /home/lijun/works/yii-application/yii_test(22): yii\base\Application->run()
#11 {main}

```


3.If common\config\test.php has:
```
        'request' => [],
```
`codecept run` will have an error:
```
1) LoginFormTest: Login correct
 Test  ../common/tests/unit/models/LoginFormTest.php:testLoginCorrect
                                                                                                                
  [yii\base\InvalidConfigException] yii\web\Request::cookieValidationKey must be configured with a secret key.  
                                                                                                                
#1  /home/lijun/works/yii-application/vendor/yiisoft/yii2/web/Request.php:1554
#2  /home/lijun/works/yii-application/vendor/yiisoft/yii2/web/Request.php:1536
#3  /home/lijun/works/yii-application/vendor/yiisoft/yii2/web/Request.php:1620
#4  /home/lijun/works/yii-application/vendor/yiisoft/yii2/web/Request.php:1602
#5  /home/lijun/works/yii-application/vendor/yiisoft/yii2/web/User.php:654
#6  /home/lijun/works/yii-application/vendor/yiisoft/yii2/web/User.php:252
#7  /home/lijun/works/yii-application/common/models/LoginForm.php:59
#8  /home/lijun/works/yii-application/common/tests/unit/models/LoginFormTest.php:63
#9  common\tests\unit\models\LoginFormTest->testLoginCorrect

ERRORS!
Tests: 38, Assertions: 126, Errors: 1.
```

**Comment by ALysogorsky** [comment]
@biaoqianwo I have the same problem. Did you solve it?

**Comment by igoryan** [comment]
+1, I have the same problem.

**Comment by craiglondon** [comment]
This same error happens when you do a new setup of the advanced template using Vagrant

https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md#installing-using-vagrant

```    y2aa: --> Install composer
    y2aa:  
    y2aa: All settings correct for using Composer
    y2aa: Downloading...
    y2aa: 
    y2aa: Composer (version 1.6.3) successfully installed to: /usr/local/bin/composer
    y2aa: Use it: php /usr/local/bin/composer
==> y2aa: Running provisioner: shell...
    y2aa: Running: /var/folders/x2/6pj6bs6x2m98qpz6dmskw56h0000gp/T/vagrant-shell20180404-62211-1bs5et4.sh
    y2aa:  
    y2aa: --> Provision-script user: vagrant
    y2aa:  
    y2aa:  
    y2aa: --> Configure composer
    y2aa:  
    y2aa: Done!
    y2aa:  
    y2aa: --> Install project dependencies
    y2aa:  
    y2aa: Loading composer repositories with package information
    y2aa: Installing dependencies (including require-dev) from lock file
    y2aa: Nothing to install or update
    y2aa: Generating autoload files
    y2aa:  
    y2aa: --> Init project
    y2aa:  
    y2aa: Yii Application Initialization Tool v1.0
    y2aa: 
    y2aa:   Start initialization ...
    y2aa:    generate backend/config/main-local.php
    y2aa:    generate backend/config/params-local.php
    y2aa:    generate backend/config/test-local.php
    y2aa:    generate backend/web/index-test.php
    y2aa:    generate backend/web/index.php
    y2aa:    generate backend/web/robots.txt
    y2aa:    generate common/config/main-local.php
    y2aa:    generate common/config/params-local.php
    y2aa:    generate common/config/test-local.php
    y2aa:    generate console/config/main-local.php
    y2aa:    generate console/config/params-local.php
    y2aa:    generate frontend/config/main-local.php
    y2aa:    generate frontend/config/params-local.php
    y2aa:    generate frontend/config/test-local.php
    y2aa:    generate frontend/web/index-test.php
    y2aa:    generate frontend/web/index.php
    y2aa:    generate frontend/web/robots.txt
    y2aa:    generate yii
    y2aa:    generate yii_test
    y2aa:    generate yii_test.bat
    y2aa:    generate cookie validation key in backend/config/main-local.php
    y2aa:    generate cookie validation key in frontend/config/main-local.php
    y2aa:       chmod 0777 backend/runtime
    y2aa:       chmod 0777 backend/web/assets
    y2aa:       chmod 0777 frontend/runtime
    y2aa:       chmod 0777 frontend/web/assets
    y2aa:       chmod 0755 yii
    y2aa:       chmod 0755 yii_test
    y2aa: 
    y2aa:   ... initialization completed.
    y2aa:  
    y2aa: --> Apply migrations
    y2aa:  
    y2aa: Yii Migration Tool (based on Yii v2.0.15.1)
    y2aa: Creating migration history table "migration"...
    y2aa: Done.
    y2aa: Total 1 new migration to be applied:
    y2aa: 	m130524_201442_init
    y2aa: *** applying m130524_201442_init
    y2aa:     > create table {{%user}} ...
    y2aa:  done (time: 0.015s)
    y2aa: *** applied m130524_201442_init (time: 0.033s)
    y2aa: 
    y2aa: 1 migration was applied.
    y2aa: 
    y2aa: Migrated up successfully.
    y2aa: Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::cookieValidationKey'
    y2aa: 
    y2aa: in /app/vendor/yiisoft/yii2/base/Component.php:209
    y2aa: 
    y2aa: Stack trace:
    y2aa: #0 /app/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('cookieValidatio...', 'test')
    y2aa: #1 /app/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(yii\console\Request), Array)
    y2aa: #2 [internal function]: yii\base\BaseObject->__construct(Array)
    y2aa: #3 /app/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
    y2aa: #4 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\console\\Req...', Array, Array)
    y2aa: #5 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\console\\Req...', Array, Array)
    y2aa: #6 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
    y2aa: #7 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
    y2aa: #8 /app/vendor/yiisoft/yii2/console/Application.php(219): yii\base\Module->get('request')
    y2aa: #9 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->getRequest()
    y2aa: #10 /app/yii_test(22): yii\base\Application->run()
    y2aa: #11 {main}

**Comment by armpogart** [comment]
@samdark 0f2a0ed breaks `common\tests\unit\models\LoginFormTest` as `cookieValidationKey` is not defined.

**Comment by armpogart** [comment]
@samdark One option would be to simply unset the key in `yii_test` - `unset($config['components']['request']['cookieValidationKey']);` as `ArrayHelper` won't recursively unset it even if we redefine the `key` in `console/config/test.php`.

**Comment by fabioaccetta** [comment]
I solved this way:

1. create a new php config file `@common/config/codeception-local.php` (this file could also be managed by `environments` and `.gitignore`)
2. put this content:
```php
<?php

return yii\helpers\ArrayHelper::merge(require __DIR__ . '/test-local.php', [
		'components' => [
			'request' => [
				'cookieValidationKey' => 'test',
			],
		],
	]);
```
3. changed `@common/codeception.yml` to load this file instead of `test-local.php`:
```yml
[...]
modules:
    config:
        Yii2:
            configFile: 'config/codeception-local.php'
[...]
```

Hope this helps.

**Comment by VojtechH** [comment]
I have created a following workaround which is slightly different from the solution presented by @fabioaccetta:

1. Created new config file `@console/config/test.php` with the following content:
```php
<?php
return [
    'components' => [
        'request' => [
            'cookieValidationKey' => new \yii\helpers\UnsetArrayValue(),
        ],
    ],
];
```
2. Updated the `yii_test` file by adding the new config as the last merged file:
```php
[...]
$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/test-local.php',
    require __DIR__ . '/console/config/main.php',
    require __DIR__ . '/console/config/main-local.php',
    require __DIR__ . '/console/config/test.php'
);
[...]
```
Note: `yii_test` is located in `environments/dev` and copied to the root by the `init` script.
