### ISSUE TITLE
Could not run Acceptance Tests, Please Help!

### ISSUE THREAD

**Issue by looqmaan** [yiisoft/yii2-app-advanced#380]
### What steps will reproduce the problem?
I followed this testing guide: https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-testing.md

### What's expected?
Expected to see results from Selenium testings.

### What do you get instead?
Got the error below
```
user@user-ubuntu16:/mnt/code/project-v2$
vendor/bin/codecept run acceptance -- -c frontend

Codeception PHP Testing Framework v2.4.4
Powered by PHPUnit 6.5.9 by Sebastian Bergmann and contributors.

Frontend\tests.acceptance Tests (1) ----------------------------------------------------------------------------------------------------------------------------
E HomeCest: Check home 
PHP Fatal error:  Uncaught Error: Call to a member function stop() on null in /mnt/code/project-v2/vendor/codeception/codeception/src/Codeception/Module/Yii2.php:346
Stack trace:
#0 /mnt/code/project-v2/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php(66): Codeception\Module\Yii2->_after(Object(Codeception\Test\Cest))
#1 /mnt/code/project-v2/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Codeception\Subscriber\Module->after(Object(Codeception\Event\TestEvent), 'test.after', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /mnt/code/project-v2/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.after', Object(Codeception\Event\TestEvent))
#3 /mnt/code/project-v2/vendor/codeception/phpunit-wrapper/src/Listener.php(133): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('test.after', Object(Codeception\Event\TestEvent))
#4 /mnt/code/project-v2/vendor/codeception/phpuni in /mnt/code/project-v2/vendor/codeception/codeception/src/Codeception/Module/Yii2.php on line 346



FATAL ERROR. TESTS NOT FINISHED.
Uncaught Error: Call to a member function stop() on null in /mnt/code/project-v2/vendor/codeception/codeception/src/Codeception/Module/Yii2.php:346
Stack trace:
#0 /mnt/code/project-v2/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php(66): Codeception\Module\Yii2->_after(Object(Codeception\Test\Cest))
#1 /mnt/code/project-v2/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Codeception\Subscriber\Module->after(Object(Codeception\Event\TestEvent), 'test.after', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /mnt/code/project-v2/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.after', Object(Codeception\Event\TestEvent))
#3 /mnt/code/project-v2/vendor/codeception/phpunit-wrapper/src/Listener.php(133): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('test.after', Object(Codeception\Event\TestEvent))
#4 /mnt/code/project-v2/vendor/codeception/phpuni 
in /mnt/code/project-v2/vendor/codeception/codeception/src/Codeception/Module/Yii2.php:346

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.15.1
| PHP version      | 7.0.30-0ubuntu0.16.04.1
| Operating system | Ubuntu 16.04.4 LTS

**Comment by Faryshta** [comment]
the problem is that the `test-local.php` file contained partial configuration for the codeception yii2 module. The #377 PR fixed this, please confirm @looqmaan

**Comment by looqmaan** [comment]
Hi @Faryshta, Thanks for letting me know the fix. If I already have an application set up using the previous version of yii2-app-advanced, how do I apply the latest patches to my app?

Thanks.

**Comment by Faryshta** [comment]
```bash
git remote add yii2app git@github.com:yiisoft/yii2-app-advanced.git
git pull yii2app master
```

then fix all conflicts and make merge

**Comment by looqmaan** [comment]
Thanks @Faryshta
