### ISSUE TITLE
After vagrant up

### ISSUE THREAD

**Issue by PetrovichevSergey** [yiisoft/yii2-app-advanced#387]
I install yii2-app-advanced and after **vagrant up** i see this error:

```
    y2aa: --> Install project dependencies
    y2aa:  
    y2aa: Loading composer repositories with package information
    y2aa: Installing dependencies (including require-dev) from lock file
    y2aa: Your requirements could not be resolved to an installable set of packages.
    y2aa: 
    y2aa:   Problem 1
    y2aa:     - symfony/browser-kit v4.1.3 requires php ^7.1.3 -> your PHP version (7.0.30) does not satisfy that requirement.
    y2aa:     - symfony/browser-kit v4.1.3 requires php ^7.1.3 -> your PHP version (7.0.30) does not satisfy that requirement.
    y2aa:     - Installation request for symfony/browser-kit v4.1.3 -> satisfiable by symfony/browser-kit[v4.1.3].
    y2aa:  
    y2aa: --> Init project
    y2aa:  
    y2aa: Yii Application Initialization Tool v1.0
    y2aa: 
    y2aa:   Start initialization ...
    y2aa:    generate backend/config/main-local.php
    y2aa:    generate backend/config/params-local.php
    y2aa:    generate backend/config/test-local.php
    y2aa:    generate backend/web/index-test.php
    y2aa:    generate backend/web/index.php
    y2aa:    generate backend/web/robots.txt
    y2aa:    generate common/config/main-local.php
    y2aa:    generate common/config/params-local.php
    y2aa:    generate common/config/test-local.php
    y2aa:    generate console/config/main-local.php
    y2aa:    generate console/config/params-local.php
    y2aa:    generate frontend/config/main-local.php
    y2aa:    generate frontend/config/params-local.php
    y2aa:    generate frontend/config/test-local.php
    y2aa:    generate frontend/web/index-test.php
    y2aa:    generate frontend/web/index.php
    y2aa:    generate frontend/web/robots.txt
    y2aa:    generate yii
    y2aa:    generate yii_test
    y2aa:    generate yii_test.bat
    y2aa:    generate cookie validation key in backend/config/main-local.php
    y2aa:    generate cookie validation key in frontend/config/main-local.php
    y2aa:       chmod 0777 backend/runtime
    y2aa:       chmod 0777 backend/web/assets
    y2aa:       chmod 0777 frontend/runtime
    y2aa:       chmod 0777 frontend/web/assets
    y2aa:       chmod 0755 yii
    y2aa:       chmod 0755 yii_test
    y2aa: 
    y2aa:   ... initialization completed.
    y2aa:  
    y2aa: --> Apply migrations
    y2aa:  
    y2aa: Yii Migration Tool (based on Yii v2.0.15.1)
    y2aa: Creating migration history table "migration"...
    y2aa: Done.
    y2aa: Total 1 new migration to be applied:
    y2aa: 	m130524_201442_init
    y2aa: *** applying m130524_201442_init
    y2aa:     > create table {{%user}} ...
    y2aa:  done (time: 0.094s)
    y2aa: *** applied m130524_201442_init (time: 0.194s)
    y2aa: 
    y2aa: 1 migration was applied.
    y2aa: 
    y2aa: Migrated up successfully.
    y2aa: Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::cookieValidationKey'
    y2aa: 
    y2aa: in /app/vendor/yiisoft/yii2/base/Component.php:209
    y2aa: 
    y2aa: Stack trace:
    y2aa: #0 /app/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('cookieValidatio...', 'test')
    y2aa: #1 /app/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(yii\console\Request), Array)
    y2aa: #2 [internal function]: yii\base\BaseObject->__construct(Array)
    y2aa: #3 /app/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
    y2aa: #4 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\console\\Req...', Array, Array)
    y2aa: #5 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\console\\Req...', Array, Array)
    y2aa: #6 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
    y2aa: #7 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('request', true)
    y2aa: #8 /app/vendor/yiisoft/yii2/console/Application.php(219): yii\base\Module->get('request')
    y2aa: #9 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->getRequest()
    y2aa: #10 /app/yii_test(22): yii\base\Application->run()
    y2aa: #11 {main}
    y2aa:  
    y2aa: --> Create bash-alias 'app' for vagrant user
    y2aa:  
    y2aa: alias app="cd /app"
    y2aa:  
    y2aa: --> Enabling colorized prompt for guest console
    y2aa:  
==> y2aa: Running provisioner: shell...
    y2aa: Running: /tmp/vagrant-shell20180806-16988-1ielhx7.sh
    y2aa:  
    y2aa: --> Provision-script user: root
    y2aa:  
    y2aa:  
    y2aa: --> Restart web-stack
    y2aa:  

==> y2aa: Machine 'y2aa' has a post `vagrant up` message. This is a message
==> y2aa: from the creator of the Vagrantfile, and not from Vagrant itself:
==> y2aa: 
==> y2aa: Frontend URL: http://y2aa-frontend.test
==> y2aa: Backend URL: http://y2aa-backend.test
```

**Comment by samdark** [comment]
Try code from master.
