### ISSUE TITLE
php yii migrate doesnt work

### ISSUE THREAD

**Issue by SusgUY446** [yiisoft/yii2-app-advanced#562]
### What steps will reproduce the problem?
running php yii migrate
### What's expected?
that it works?
### What do you get instead?
this error:
```
PS C:\xampp\htdocs\phptube> php yii migrate
Yii Migration Tool (based on Yii v2.0.49.3)

Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it'

in C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Connection.php:648

Error Info:
Array
(
    [0] => HY000
    [1] => 2002
    [2] => No connection could be made because the target machine actively refused it
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it'

in C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Connection.php:722

Stack trace:
#0 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Connection.php(722): PDO->__construct('mysql:host=loca...', 'root', Object(SensitiveParameterValue), NULL)
#1 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Connection.php(637): yii\db\Connection->createPdoInstance()
#2 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Connection.php(1067): yii\db\Connection->open()
#3 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Connection.php(1054): yii\db\Connection->getMasterPdo()
#4 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Command.php(261): yii\db\Connection->getSlavePdo(true)
#5 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Command.php(1181): yii\db\Command->prepare(true)
#6 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Command.php(417): yii\db\Command->queryInternal('fetchAll', NULL)
#7 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\mysql\Schema.php(328): yii\db\Command->queryAll()
#8 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\mysql\Schema.php(133): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))
#9 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Schema.php(756): yii\db\mysql\Schema->loadTableSchema('migration')
#10 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\db\Schema.php(192): yii\db\Schema->getTableMetadata('{{%migration}}', 'schema', true)
#11 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\console\controllers\MigrateController.php(211): yii\db\Schema->getTableSchema('{{%migration}}', true)
#12 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(908): yii\console\controllers\MigrateController->getMigrationHistory(NULL)
#13 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(183): yii\console\controllers\BaseMigrateController->getNewMigrations()
#14 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#15 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\console\Controller.php(180): yii\base\Controller->runAction('', Array)
#18 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\base\Module.php(552): yii\console\Controller->runAction('', Array)
#19 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate', Array)
#20 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate', Array)
#21 C:\xampp\htdocs\phptube\vendor\yiisoft\yii2\base\Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#22 C:\xampp\htdocs\phptube\yii(23): yii\base\Application->run()
#23 {main}
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | latest
| PHP version      | XAMPP PHP 8.2
| Operating system | windows 11

**Comment by SusgUY446** [comment]
fixed it. for anyone else here is what i changed:
in common > config > main-local.php
i changed 
"
    'components' => [
        'db' => [
            'class' => \yii\db\Connection::class,
            'dsn' => 'mysql:host=localhost:3306;dbname=phptube',
            'username' => 'root',
            'password' => '',
            'charset' => 'utf8',
        ],
"
to 
"
    'components' => [
        'db' => [
            'class' => \yii\db\Connection::class,
            'dsn' => 'mysql:host=127.0.0.1:3306;dbname=phptube',
            'username' => 'root',
            'password' => '',
            'charset' => 'utf8',
        ],
"
